/* Generated by restful-react */

import React from 'react';
import { Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface DeviceRegistrationInput {
  deviceRegistrationId?: string | null;
}

export interface DeviceRegistrationDto {
  id?: string;
  deviceRegistrationId?: string | null;
  personId?: string;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface DeviceRegistrationDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: DeviceRegistrationDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface DeviceRegistrationCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceRegistrationCreateProps = Omit<
  MutateProps<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationCreateQueryParams,
    DeviceRegistrationInput,
    void
  >,
  'path' | 'verb'
>;

export const DeviceRegistrationCreate = (props: DeviceRegistrationCreateProps) => (
  <Mutate<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationCreateQueryParams,
    DeviceRegistrationInput,
    void
  >
    verb="POST"
    path={`/api/services/app/DeviceRegistration/Create`}
    {...props}
  />
);

export type UseDeviceRegistrationCreateProps = Omit<
  UseMutateProps<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationCreateQueryParams,
    DeviceRegistrationInput,
    void
  >,
  'path' | 'verb'
>;

export const useDeviceRegistrationCreate = (props: UseDeviceRegistrationCreateProps) =>
  useMutate<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationCreateQueryParams,
    DeviceRegistrationInput,
    void
  >('POST', `/api/services/app/DeviceRegistration/Create`, props);

export interface DeviceRegistrationUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceRegistrationUpdateProps = Omit<
  MutateProps<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationUpdateQueryParams,
    DeviceRegistrationInput,
    void
  >,
  'path' | 'verb'
>;

export const DeviceRegistrationUpdate = (props: DeviceRegistrationUpdateProps) => (
  <Mutate<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationUpdateQueryParams,
    DeviceRegistrationInput,
    void
  >
    verb="PUT"
    path={`/api/services/app/DeviceRegistration/Update`}
    {...props}
  />
);

export type UseDeviceRegistrationUpdateProps = Omit<
  UseMutateProps<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationUpdateQueryParams,
    DeviceRegistrationInput,
    void
  >,
  'path' | 'verb'
>;

export const useDeviceRegistrationUpdate = (props: UseDeviceRegistrationUpdateProps) =>
  useMutate<
    DeviceRegistrationDtoAjaxResponse,
    AjaxResponseBase,
    DeviceRegistrationUpdateQueryParams,
    DeviceRegistrationInput,
    void
  >('PUT', `/api/services/app/DeviceRegistration/Update`, props);
