/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface DeviceForceUpdateDto {
  id?: string;
  name?: string | null;
  description?: string | null;
  appStoreUrl?: string | null;
  osType?: number | null;
  versionNo?: number | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface DeviceForceUpdateDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: DeviceForceUpdateDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface DeviceForceUpdateDtoPagedResultDto {
  items?: DeviceForceUpdateDto[] | null;
  totalCount?: number;
}

export interface DeviceForceUpdateDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: DeviceForceUpdateDtoPagedResultDto;
}

export interface DeviceForceUpdateCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceForceUpdateCreateProps = Omit<
  MutateProps<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateCreateQueryParams,
    DeviceForceUpdateDto,
    void
  >,
  'path' | 'verb'
>;

export const DeviceForceUpdateCreate = (props: DeviceForceUpdateCreateProps) => (
  <Mutate<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateCreateQueryParams,
    DeviceForceUpdateDto,
    void
  >
    verb="POST"
    path={`/api/services/app/DeviceForceUpdate/Create`}
    {...props}
  />
);

export type UseDeviceForceUpdateCreateProps = Omit<
  UseMutateProps<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateCreateQueryParams,
    DeviceForceUpdateDto,
    void
  >,
  'path' | 'verb'
>;

export const useDeviceForceUpdateCreate = (props: UseDeviceForceUpdateCreateProps) =>
  useMutate<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateCreateQueryParams,
    DeviceForceUpdateDto,
    void
  >('POST', `/api/services/app/DeviceForceUpdate/Create`, props);

export interface DeviceForceUpdateGetForceUpdateByOSTypeQueryParams {
  osType?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceForceUpdateGetForceUpdateByOSTypeProps = Omit<
  GetProps<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateGetForceUpdateByOSTypeQueryParams,
    void
  >,
  'path'
>;

export const DeviceForceUpdateGetForceUpdateByOSType = (props: DeviceForceUpdateGetForceUpdateByOSTypeProps) => (
  <Get<DeviceForceUpdateDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetForceUpdateByOSTypeQueryParams, void>
    path={`/api/services/app/DeviceForceUpdate/GetForceUpdateByOSType`}
    {...props}
  />
);

export type UseDeviceForceUpdateGetForceUpdateByOSTypeProps = Omit<
  UseGetProps<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateGetForceUpdateByOSTypeQueryParams,
    void
  >,
  'path'
>;

export const useDeviceForceUpdateGetForceUpdateByOSType = (props: UseDeviceForceUpdateGetForceUpdateByOSTypeProps) =>
  useGet<DeviceForceUpdateDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetForceUpdateByOSTypeQueryParams, void>(
    `/api/services/app/DeviceForceUpdate/GetForceUpdateByOSType`,
    props
  );

export interface DeviceForceUpdateGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceForceUpdateGetProps = Omit<
  GetProps<DeviceForceUpdateDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetQueryParams, void>,
  'path'
>;

export const DeviceForceUpdateGet = (props: DeviceForceUpdateGetProps) => (
  <Get<DeviceForceUpdateDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetQueryParams, void>
    path={`/api/services/app/DeviceForceUpdate/Get`}
    {...props}
  />
);

export type UseDeviceForceUpdateGetProps = Omit<
  UseGetProps<DeviceForceUpdateDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetQueryParams, void>,
  'path'
>;

export const useDeviceForceUpdateGet = (props: UseDeviceForceUpdateGetProps) =>
  useGet<DeviceForceUpdateDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetQueryParams, void>(
    `/api/services/app/DeviceForceUpdate/Get`,
    props
  );

export interface DeviceForceUpdateGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceForceUpdateGetAllProps = Omit<
  GetProps<DeviceForceUpdateDtoPagedResultDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetAllQueryParams, void>,
  'path'
>;

export const DeviceForceUpdateGetAll = (props: DeviceForceUpdateGetAllProps) => (
  <Get<DeviceForceUpdateDtoPagedResultDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetAllQueryParams, void>
    path={`/api/services/app/DeviceForceUpdate/GetAll`}
    {...props}
  />
);

export type UseDeviceForceUpdateGetAllProps = Omit<
  UseGetProps<
    DeviceForceUpdateDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateGetAllQueryParams,
    void
  >,
  'path'
>;

export const useDeviceForceUpdateGetAll = (props: UseDeviceForceUpdateGetAllProps) =>
  useGet<DeviceForceUpdateDtoPagedResultDtoAjaxResponse, AjaxResponseBase, DeviceForceUpdateGetAllQueryParams, void>(
    `/api/services/app/DeviceForceUpdate/GetAll`,
    props
  );

export interface DeviceForceUpdateUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceForceUpdateUpdateProps = Omit<
  MutateProps<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateUpdateQueryParams,
    DeviceForceUpdateDto,
    void
  >,
  'path' | 'verb'
>;

export const DeviceForceUpdateUpdate = (props: DeviceForceUpdateUpdateProps) => (
  <Mutate<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateUpdateQueryParams,
    DeviceForceUpdateDto,
    void
  >
    verb="PUT"
    path={`/api/services/app/DeviceForceUpdate/Update`}
    {...props}
  />
);

export type UseDeviceForceUpdateUpdateProps = Omit<
  UseMutateProps<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateUpdateQueryParams,
    DeviceForceUpdateDto,
    void
  >,
  'path' | 'verb'
>;

export const useDeviceForceUpdateUpdate = (props: UseDeviceForceUpdateUpdateProps) =>
  useMutate<
    DeviceForceUpdateDtoAjaxResponse,
    AjaxResponseBase,
    DeviceForceUpdateUpdateQueryParams,
    DeviceForceUpdateDto,
    void
  >('PUT', `/api/services/app/DeviceForceUpdate/Update`, props);

export interface DeviceForceUpdateDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type DeviceForceUpdateDeleteProps = Omit<
  MutateProps<void, unknown, DeviceForceUpdateDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const DeviceForceUpdateDelete = (props: DeviceForceUpdateDeleteProps) => (
  <Mutate<void, unknown, DeviceForceUpdateDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/DeviceForceUpdate/Delete`}
    {...props}
  />
);

export type UseDeviceForceUpdateDeleteProps = Omit<
  UseMutateProps<void, unknown, DeviceForceUpdateDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useDeviceForceUpdateDelete = (props: UseDeviceForceUpdateDeleteProps) =>
  useMutate<void, unknown, DeviceForceUpdateDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/DeviceForceUpdate/Delete`,
    { ...props }
  );
