/* Generated by restful-react */

import React from 'react';
import { Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface SendNotificationToTopicInput {
  body: string;
  title?: string | null;
  data?: {
    [key: string]: string;
  } | null;
  topic: string;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface StringAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: string | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface SendNotificationToPersonInput {
  body: string;
  title?: string | null;
  data?: {
    [key: string]: string;
  } | null;
  personId: string;
}

export interface FirebaseUpdateSettingsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type FirebaseUpdateSettingsProps = Omit<
  MutateProps<void, unknown, FirebaseUpdateSettingsQueryParams, void, void>,
  'path' | 'verb'
>;

export const FirebaseUpdateSettings = (props: FirebaseUpdateSettingsProps) => (
  <Mutate<void, unknown, FirebaseUpdateSettingsQueryParams, void, void>
    verb="POST"
    path={`/api/services/SheshaFirebase/Firebase/UpdateSettings`}
    {...props}
  />
);

export type UseFirebaseUpdateSettingsProps = Omit<
  UseMutateProps<void, unknown, FirebaseUpdateSettingsQueryParams, void, void>,
  'path' | 'verb'
>;

export const useFirebaseUpdateSettings = (props: UseFirebaseUpdateSettingsProps) =>
  useMutate<void, unknown, FirebaseUpdateSettingsQueryParams, void, void>(
    'POST',
    `/api/services/SheshaFirebase/Firebase/UpdateSettings`,
    props
  );

export interface FirebaseSendNotificationToTopicQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type FirebaseSendNotificationToTopicProps = Omit<
  MutateProps<
    StringAjaxResponse,
    AjaxResponseBase,
    FirebaseSendNotificationToTopicQueryParams,
    SendNotificationToTopicInput,
    void
  >,
  'path' | 'verb'
>;

export const FirebaseSendNotificationToTopic = (props: FirebaseSendNotificationToTopicProps) => (
  <Mutate<
    StringAjaxResponse,
    AjaxResponseBase,
    FirebaseSendNotificationToTopicQueryParams,
    SendNotificationToTopicInput,
    void
  >
    verb="POST"
    path={`/api/services/SheshaFirebase/Firebase/SendNotificationToTopic`}
    {...props}
  />
);

export type UseFirebaseSendNotificationToTopicProps = Omit<
  UseMutateProps<
    StringAjaxResponse,
    AjaxResponseBase,
    FirebaseSendNotificationToTopicQueryParams,
    SendNotificationToTopicInput,
    void
  >,
  'path' | 'verb'
>;

export const useFirebaseSendNotificationToTopic = (props: UseFirebaseSendNotificationToTopicProps) =>
  useMutate<
    StringAjaxResponse,
    AjaxResponseBase,
    FirebaseSendNotificationToTopicQueryParams,
    SendNotificationToTopicInput,
    void
  >('POST', `/api/services/SheshaFirebase/Firebase/SendNotificationToTopic`, props);

export interface FirebaseSendNotificationToPersonQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type FirebaseSendNotificationToPersonProps = Omit<
  MutateProps<void, unknown, FirebaseSendNotificationToPersonQueryParams, SendNotificationToPersonInput, void>,
  'path' | 'verb'
>;

export const FirebaseSendNotificationToPerson = (props: FirebaseSendNotificationToPersonProps) => (
  <Mutate<void, unknown, FirebaseSendNotificationToPersonQueryParams, SendNotificationToPersonInput, void>
    verb="POST"
    path={`/api/services/SheshaFirebase/Firebase/SendNotificationToPerson`}
    {...props}
  />
);

export type UseFirebaseSendNotificationToPersonProps = Omit<
  UseMutateProps<void, unknown, FirebaseSendNotificationToPersonQueryParams, SendNotificationToPersonInput, void>,
  'path' | 'verb'
>;

export const useFirebaseSendNotificationToPerson = (props: UseFirebaseSendNotificationToPersonProps) =>
  useMutate<void, unknown, FirebaseSendNotificationToPersonQueryParams, SendNotificationToPersonInput, void>(
    'POST',
    `/api/services/SheshaFirebase/Firebase/SendNotificationToPerson`,
    props
  );
