/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface AutocompleteItemDto {
  value?: string | null;
  displayText?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AutocompleteItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AutocompleteItemDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  displayText?: string | null;
}

export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

export interface GmaAreaDto {
  id?: string;
  name?: string | null;
  parentArea?: GuidNullableEntityWithDisplayNameDto;
  areaType?: ReferenceListItemValueDto;
}

export interface GmaAreaDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: GmaAreaDto;
}

export interface GmaAreaDtoPagedResultDto {
  items?: GmaAreaDto[] | null;
  totalCount?: number;
}

export interface GmaAreaDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: GmaAreaDtoPagedResultDto;
}

export interface GmaAreaCreateDto {
  name?: string | null;
  shortName?: string | null;
  parentArea?: GuidNullableEntityWithDisplayNameDto;
  comments?: string | null;
  areaType?: ReferenceListItemValueDto;
}

export interface GmaAreaUpdateDto {
  id?: string;
  name?: string | null;
  shortName?: string | null;
  comments?: string | null;
  areaType?: ReferenceListItemValueDto;
}

export interface GmaAreasProvincesAutocompleteQueryParams {
  term?: string | null;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasProvincesAutocompleteProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasProvincesAutocompleteQueryParams, void>,
  'path'
>;

export const GmaAreasProvincesAutocomplete = (props: GmaAreasProvincesAutocompleteProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasProvincesAutocompleteQueryParams, void>
    path={`/api/services/Gma/GmaAreas/ProvincesAutocomplete`}
    {...props}
  />
);

export type UseGmaAreasProvincesAutocompleteProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasProvincesAutocompleteQueryParams, void>,
  'path'
>;

export const useGmaAreasProvincesAutocomplete = (props: UseGmaAreasProvincesAutocompleteProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasProvincesAutocompleteQueryParams, void>(
    `/api/services/Gma/GmaAreas/ProvincesAutocomplete`,
    props
  );

export interface GmaAreasRegionsAutocompleteQueryParams {
  term?: string | null;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasRegionsAutocompleteProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasRegionsAutocompleteQueryParams, void>,
  'path'
>;

export const GmaAreasRegionsAutocomplete = (props: GmaAreasRegionsAutocompleteProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasRegionsAutocompleteQueryParams, void>
    path={`/api/services/Gma/GmaAreas/RegionsAutocomplete`}
    {...props}
  />
);

export type UseGmaAreasRegionsAutocompleteProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasRegionsAutocompleteQueryParams, void>,
  'path'
>;

export const useGmaAreasRegionsAutocomplete = (props: UseGmaAreasRegionsAutocompleteProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasRegionsAutocompleteQueryParams, void>(
    `/api/services/Gma/GmaAreas/RegionsAutocomplete`,
    props
  );

export interface GmaAreasBranchesAutocompleteQueryParams {
  term?: string | null;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasBranchesAutocompleteProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasBranchesAutocompleteQueryParams, void>,
  'path'
>;

export const GmaAreasBranchesAutocomplete = (props: GmaAreasBranchesAutocompleteProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasBranchesAutocompleteQueryParams, void>
    path={`/api/services/Gma/GmaAreas/BranchesAutocomplete`}
    {...props}
  />
);

export type UseGmaAreasBranchesAutocompleteProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasBranchesAutocompleteQueryParams, void>,
  'path'
>;

export const useGmaAreasBranchesAutocomplete = (props: UseGmaAreasBranchesAutocompleteProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, GmaAreasBranchesAutocompleteQueryParams, void>(
    `/api/services/Gma/GmaAreas/BranchesAutocomplete`,
    props
  );

export interface GmaAreasGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasGetProps = Omit<
  GetProps<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasGetQueryParams, void>,
  'path'
>;

export const GmaAreasGet = (props: GmaAreasGetProps) => (
  <Get<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasGetQueryParams, void>
    path={`/api/services/Gma/GmaAreas/Get`}
    {...props}
  />
);

export type UseGmaAreasGetProps = Omit<
  UseGetProps<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasGetQueryParams, void>,
  'path'
>;

export const useGmaAreasGet = (props: UseGmaAreasGetProps) =>
  useGet<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasGetQueryParams, void>(
    `/api/services/Gma/GmaAreas/Get`,
    props
  );

export interface GmaAreasGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasGetAllProps = Omit<
  GetProps<GmaAreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, GmaAreasGetAllQueryParams, void>,
  'path'
>;

export const GmaAreasGetAll = (props: GmaAreasGetAllProps) => (
  <Get<GmaAreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, GmaAreasGetAllQueryParams, void>
    path={`/api/services/Gma/GmaAreas/GetAll`}
    {...props}
  />
);

export type UseGmaAreasGetAllProps = Omit<
  UseGetProps<GmaAreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, GmaAreasGetAllQueryParams, void>,
  'path'
>;

export const useGmaAreasGetAll = (props: UseGmaAreasGetAllProps) =>
  useGet<GmaAreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, GmaAreasGetAllQueryParams, void>(
    `/api/services/Gma/GmaAreas/GetAll`,
    props
  );

export interface GmaAreasCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasCreateProps = Omit<
  MutateProps<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasCreateQueryParams, GmaAreaCreateDto, void>,
  'path' | 'verb'
>;

export const GmaAreasCreate = (props: GmaAreasCreateProps) => (
  <Mutate<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasCreateQueryParams, GmaAreaCreateDto, void>
    verb="POST"
    path={`/api/services/Gma/GmaAreas/Create`}
    {...props}
  />
);

export type UseGmaAreasCreateProps = Omit<
  UseMutateProps<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasCreateQueryParams, GmaAreaCreateDto, void>,
  'path' | 'verb'
>;

export const useGmaAreasCreate = (props: UseGmaAreasCreateProps) =>
  useMutate<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasCreateQueryParams, GmaAreaCreateDto, void>(
    'POST',
    `/api/services/Gma/GmaAreas/Create`,
    props
  );

export interface GmaAreasUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasUpdateProps = Omit<
  MutateProps<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasUpdateQueryParams, GmaAreaUpdateDto, void>,
  'path' | 'verb'
>;

export const GmaAreasUpdate = (props: GmaAreasUpdateProps) => (
  <Mutate<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasUpdateQueryParams, GmaAreaUpdateDto, void>
    verb="PUT"
    path={`/api/services/Gma/GmaAreas/Update`}
    {...props}
  />
);

export type UseGmaAreasUpdateProps = Omit<
  UseMutateProps<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasUpdateQueryParams, GmaAreaUpdateDto, void>,
  'path' | 'verb'
>;

export const useGmaAreasUpdate = (props: UseGmaAreasUpdateProps) =>
  useMutate<GmaAreaDtoAjaxResponse, AjaxResponseBase, GmaAreasUpdateQueryParams, GmaAreaUpdateDto, void>(
    'PUT',
    `/api/services/Gma/GmaAreas/Update`,
    props
  );

export interface GmaAreasDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type GmaAreasDeleteProps = Omit<
  MutateProps<void, unknown, GmaAreasDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const GmaAreasDelete = (props: GmaAreasDeleteProps) => (
  <Mutate<void, unknown, GmaAreasDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/Gma/GmaAreas/Delete`}
    {...props}
  />
);

export type UseGmaAreasDeleteProps = Omit<
  UseMutateProps<void, unknown, GmaAreasDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useGmaAreasDelete = (props: UseGmaAreasDeleteProps) =>
  useMutate<void, unknown, GmaAreasDeleteQueryParams, void, void>('DELETE', `/api/services/Gma/GmaAreas/Delete`, {
    ...props,
  });
