/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface MembershipRegistrationSettingsDto {
  [key: string]: any;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface MembershipRegistrationSettingsDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: MembershipRegistrationSettingsDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface MembershipRegistrationSettingsUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type MembershipRegistrationSettingsUpdateProps = Omit<
  MutateProps<void, unknown, MembershipRegistrationSettingsUpdateQueryParams, MembershipRegistrationSettingsDto, void>,
  'path' | 'verb'
>;

export const MembershipRegistrationSettingsUpdate = (props: MembershipRegistrationSettingsUpdateProps) => (
  <Mutate<void, unknown, MembershipRegistrationSettingsUpdateQueryParams, MembershipRegistrationSettingsDto, void>
    verb="POST"
    path={`/api/services/Gma/MembershipRegistrationSettings/Update`}
    {...props}
  />
);

export type UseMembershipRegistrationSettingsUpdateProps = Omit<
  UseMutateProps<
    void,
    unknown,
    MembershipRegistrationSettingsUpdateQueryParams,
    MembershipRegistrationSettingsDto,
    void
  >,
  'path' | 'verb'
>;

export const useMembershipRegistrationSettingsUpdate = (props: UseMembershipRegistrationSettingsUpdateProps) =>
  useMutate<void, unknown, MembershipRegistrationSettingsUpdateQueryParams, MembershipRegistrationSettingsDto, void>(
    'POST',
    `/api/services/Gma/MembershipRegistrationSettings/Update`,
    props
  );

export interface MembershipRegistrationSettingsGetQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type MembershipRegistrationSettingsGetProps = Omit<
  GetProps<
    MembershipRegistrationSettingsDtoAjaxResponse,
    AjaxResponseBase,
    MembershipRegistrationSettingsGetQueryParams,
    void
  >,
  'path'
>;

export const MembershipRegistrationSettingsGet = (props: MembershipRegistrationSettingsGetProps) => (
  <Get<
    MembershipRegistrationSettingsDtoAjaxResponse,
    AjaxResponseBase,
    MembershipRegistrationSettingsGetQueryParams,
    void
  >
    path={`/api/services/Gma/MembershipRegistrationSettings/Get`}
    {...props}
  />
);

export type UseMembershipRegistrationSettingsGetProps = Omit<
  UseGetProps<
    MembershipRegistrationSettingsDtoAjaxResponse,
    AjaxResponseBase,
    MembershipRegistrationSettingsGetQueryParams,
    void
  >,
  'path'
>;

export const useMembershipRegistrationSettingsGet = (props: UseMembershipRegistrationSettingsGetProps) =>
  useGet<
    MembershipRegistrationSettingsDtoAjaxResponse,
    AjaxResponseBase,
    MembershipRegistrationSettingsGetQueryParams,
    void
  >(`/api/services/Gma/MembershipRegistrationSettings/Get`, props);
