/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface AutocompleteItemDto {
  value?: string | null;
  displayText?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AutocompleteItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AutocompleteItemDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface MetadataEntityTypeAutocompleteQueryParams {
  term?: string | null;
  selectedValue?: string | null;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type MetadataEntityTypeAutocompleteProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, MetadataEntityTypeAutocompleteQueryParams, void>,
  'path'
>;

export const MetadataEntityTypeAutocomplete = (props: MetadataEntityTypeAutocompleteProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, MetadataEntityTypeAutocompleteQueryParams, void>
    path={`/api/services/app/Metadata/EntityTypeAutocomplete`}
    {...props}
  />
);

export type UseMetadataEntityTypeAutocompleteProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, MetadataEntityTypeAutocompleteQueryParams, void>,
  'path'
>;

export const useMetadataEntityTypeAutocomplete = (props: UseMetadataEntityTypeAutocompleteProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, MetadataEntityTypeAutocompleteQueryParams, void>(
    `/api/services/app/Metadata/EntityTypeAutocomplete`,
    props
  );
