/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface StringListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: string[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface AutocompleteItemDto {
  value?: string | null;
  displayText?: string | null;
}

export interface AutocompleteItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AutocompleteItemDto[] | null;
}

export interface NewDataTableGetTableIdsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NewDataTableGetTableIdsProps = Omit<
  GetProps<StringListAjaxResponse, AjaxResponseBase, NewDataTableGetTableIdsQueryParams, void>,
  'path'
>;

export const NewDataTableGetTableIds = (props: NewDataTableGetTableIdsProps) => (
  <Get<StringListAjaxResponse, AjaxResponseBase, NewDataTableGetTableIdsQueryParams, void>
    path={`/api/services/Shesha/NewDataTable/GetTableIds`}
    {...props}
  />
);

export type UseNewDataTableGetTableIdsProps = Omit<
  UseGetProps<StringListAjaxResponse, AjaxResponseBase, NewDataTableGetTableIdsQueryParams, void>,
  'path'
>;

export const useNewDataTableGetTableIds = (props: UseNewDataTableGetTableIdsProps) =>
  useGet<StringListAjaxResponse, AjaxResponseBase, NewDataTableGetTableIdsQueryParams, void>(
    `/api/services/Shesha/NewDataTable/GetTableIds`,
    props
  );

export interface NewDataTableTableIdAutocompleteQueryParams {
  term?: string | null;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NewDataTableTableIdAutocompleteProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, NewDataTableTableIdAutocompleteQueryParams, void>,
  'path'
>;

export const NewDataTableTableIdAutocomplete = (props: NewDataTableTableIdAutocompleteProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, NewDataTableTableIdAutocompleteQueryParams, void>
    path={`/api/services/Shesha/NewDataTable/TableIdAutocomplete`}
    {...props}
  />
);

export type UseNewDataTableTableIdAutocompleteProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, NewDataTableTableIdAutocompleteQueryParams, void>,
  'path'
>;

export const useNewDataTableTableIdAutocomplete = (props: UseNewDataTableTableIdAutocompleteProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, NewDataTableTableIdAutocompleteQueryParams, void>(
    `/api/services/Shesha/NewDataTable/TableIdAutocomplete`,
    props
  );
