/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';
export const SPEC_VERSION = 'v1';

export interface NHibernateGetConventionsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NHibernateGetConventionsProps = Omit<
  GetProps<string, unknown, NHibernateGetConventionsQueryParams, void>,
  'path'
>;

export const NHibernateGetConventions = (props: NHibernateGetConventionsProps) => (
  <Get<string, unknown, NHibernateGetConventionsQueryParams, void>
    path={`/api/services/Shesha/NHibernate/GetConventions`}
    {...props}
  />
);

export type UseNHibernateGetConventionsProps = Omit<
  UseGetProps<string, unknown, NHibernateGetConventionsQueryParams, void>,
  'path'
>;

export const useNHibernateGetConventions = (props: UseNHibernateGetConventionsProps) =>
  useGet<string, unknown, NHibernateGetConventionsQueryParams, void>(
    `/api/services/Shesha/NHibernate/GetConventions`,
    props
  );
