/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  displayText?: string | null;
}

export interface ProcessConfigurationDocumentTemplateDto {
  id?: string;
  name?: string | null;
  description?: string | null;
  sortOrder?: number;
  processConfiguration?: GuidNullableEntityWithDisplayNameDto;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ProcessConfigurationDocumentTemplateDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ProcessConfigurationDocumentTemplateDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ProcessConfigurationDocumentTemplateDtoPagedResultDto {
  items?: ProcessConfigurationDocumentTemplateDto[] | null;
  totalCount?: number;
}

export interface ProcessConfigurationDocumentTemplateDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ProcessConfigurationDocumentTemplateDtoPagedResultDto;
}

export interface ProcessConfigurationDocumentTemplateCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ProcessConfigurationDocumentTemplateCreateProps = Omit<
  MutateProps<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateCreateQueryParams,
    void,
    void
  >,
  'path' | 'verb'
>;

export const ProcessConfigurationDocumentTemplateCreate = (props: ProcessConfigurationDocumentTemplateCreateProps) => (
  <Mutate<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateCreateQueryParams,
    void,
    void
  >
    verb="POST"
    path={`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Create`}
    {...props}
  />
);

export type UseProcessConfigurationDocumentTemplateCreateProps = Omit<
  UseMutateProps<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateCreateQueryParams,
    void,
    void
  >,
  'path' | 'verb'
>;

export const useProcessConfigurationDocumentTemplateCreate = (
  props: UseProcessConfigurationDocumentTemplateCreateProps
) =>
  useMutate<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateCreateQueryParams,
    void,
    void
  >('POST', `/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Create`, props);

export interface ProcessConfigurationDocumentTemplateGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ProcessConfigurationDocumentTemplateGetProps = Omit<
  GetProps<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetQueryParams,
    void
  >,
  'path'
>;

export const ProcessConfigurationDocumentTemplateGet = (props: ProcessConfigurationDocumentTemplateGetProps) => (
  <Get<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetQueryParams,
    void
  >
    path={`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Get`}
    {...props}
  />
);

export type UseProcessConfigurationDocumentTemplateGetProps = Omit<
  UseGetProps<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetQueryParams,
    void
  >,
  'path'
>;

export const useProcessConfigurationDocumentTemplateGet = (props: UseProcessConfigurationDocumentTemplateGetProps) =>
  useGet<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetQueryParams,
    void
  >(`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Get`, props);

export interface ProcessConfigurationDocumentTemplateGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ProcessConfigurationDocumentTemplateGetAllProps = Omit<
  GetProps<
    ProcessConfigurationDocumentTemplateDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetAllQueryParams,
    void
  >,
  'path'
>;

export const ProcessConfigurationDocumentTemplateGetAll = (props: ProcessConfigurationDocumentTemplateGetAllProps) => (
  <Get<
    ProcessConfigurationDocumentTemplateDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetAllQueryParams,
    void
  >
    path={`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/GetAll`}
    {...props}
  />
);

export type UseProcessConfigurationDocumentTemplateGetAllProps = Omit<
  UseGetProps<
    ProcessConfigurationDocumentTemplateDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetAllQueryParams,
    void
  >,
  'path'
>;

export const useProcessConfigurationDocumentTemplateGetAll = (
  props: UseProcessConfigurationDocumentTemplateGetAllProps
) =>
  useGet<
    ProcessConfigurationDocumentTemplateDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateGetAllQueryParams,
    void
  >(`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/GetAll`, props);

export interface ProcessConfigurationDocumentTemplateUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ProcessConfigurationDocumentTemplateUpdateProps = Omit<
  MutateProps<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateUpdateQueryParams,
    ProcessConfigurationDocumentTemplateDto,
    void
  >,
  'path' | 'verb'
>;

export const ProcessConfigurationDocumentTemplateUpdate = (props: ProcessConfigurationDocumentTemplateUpdateProps) => (
  <Mutate<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateUpdateQueryParams,
    ProcessConfigurationDocumentTemplateDto,
    void
  >
    verb="PUT"
    path={`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Update`}
    {...props}
  />
);

export type UseProcessConfigurationDocumentTemplateUpdateProps = Omit<
  UseMutateProps<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateUpdateQueryParams,
    ProcessConfigurationDocumentTemplateDto,
    void
  >,
  'path' | 'verb'
>;

export const useProcessConfigurationDocumentTemplateUpdate = (
  props: UseProcessConfigurationDocumentTemplateUpdateProps
) =>
  useMutate<
    ProcessConfigurationDocumentTemplateDtoAjaxResponse,
    AjaxResponseBase,
    ProcessConfigurationDocumentTemplateUpdateQueryParams,
    ProcessConfigurationDocumentTemplateDto,
    void
  >('PUT', `/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Update`, props);

export interface ProcessConfigurationDocumentTemplateDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ProcessConfigurationDocumentTemplateDeleteProps = Omit<
  MutateProps<void, unknown, ProcessConfigurationDocumentTemplateDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const ProcessConfigurationDocumentTemplateDelete = (props: ProcessConfigurationDocumentTemplateDeleteProps) => (
  <Mutate<void, unknown, ProcessConfigurationDocumentTemplateDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Delete`}
    {...props}
  />
);

export type UseProcessConfigurationDocumentTemplateDeleteProps = Omit<
  UseMutateProps<void, unknown, ProcessConfigurationDocumentTemplateDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useProcessConfigurationDocumentTemplateDelete = (
  props: UseProcessConfigurationDocumentTemplateDeleteProps
) =>
  useMutate<void, unknown, ProcessConfigurationDocumentTemplateDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/SheshaWorkflow/ProcessConfigurationDocumentTemplate/Delete`,
    { ...props }
  );
