/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface WorkflowExecutionLogResponseItem {
  actionText?: string | null;
  completedBy?: string | null;
  completedOn?: string;
}

export interface WorkflowExecutionLogResponse {
  items?: WorkflowExecutionLogResponseItem[] | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface WorkflowExecutionLogResponseAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: WorkflowExecutionLogResponse;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ProcessableEntityPastTimeLineQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export interface ProcessableEntityPastTimeLinePathParams {
  id: string;
}

export type ProcessableEntityPastTimeLineProps = Omit<
  GetProps<
    WorkflowExecutionLogResponseAjaxResponse,
    AjaxResponseBase,
    ProcessableEntityPastTimeLineQueryParams,
    ProcessableEntityPastTimeLinePathParams
  >,
  'path'
> &
  ProcessableEntityPastTimeLinePathParams;

export const ProcessableEntityPastTimeLine = ({ id, ...props }: ProcessableEntityPastTimeLineProps) => (
  <Get<
    WorkflowExecutionLogResponseAjaxResponse,
    AjaxResponseBase,
    ProcessableEntityPastTimeLineQueryParams,
    ProcessableEntityPastTimeLinePathParams
  >
    path={`/api/services/SheshaWorkflow/ProcessableEntity/${id}/PastTimeLine`}
    {...props}
  />
);

export type UseProcessableEntityPastTimeLineProps = Omit<
  UseGetProps<
    WorkflowExecutionLogResponseAjaxResponse,
    AjaxResponseBase,
    ProcessableEntityPastTimeLineQueryParams,
    ProcessableEntityPastTimeLinePathParams
  >,
  'path'
> &
  ProcessableEntityPastTimeLinePathParams;

export const useProcessableEntityPastTimeLine = ({ id, ...props }: UseProcessableEntityPastTimeLineProps) =>
  useGet<
    WorkflowExecutionLogResponseAjaxResponse,
    AjaxResponseBase,
    ProcessableEntityPastTimeLineQueryParams,
    ProcessableEntityPastTimeLinePathParams
  >(
    (paramsInPath: ProcessableEntityPastTimeLinePathParams) =>
      `/api/services/SheshaWorkflow/ProcessableEntity/${paramsInPath.id}/PastTimeLine`,
    { pathParams: { id }, ...props }
  );
