/* Generated by restful-react */

import React from 'react';
import { Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';

export interface WorkflowHighLevelAssigneeResolveQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type WorkflowHighLevelAssigneeResolveProps = Omit<
  MutateProps<void, unknown, WorkflowHighLevelAssigneeResolveQueryParams, void, void>,
  'path' | 'verb'
>;

export const WorkflowHighLevelAssigneeResolve = (props: WorkflowHighLevelAssigneeResolveProps) => (
  <Mutate<void, unknown, WorkflowHighLevelAssigneeResolveQueryParams, void, void>
    verb="POST"
    path={`/api/services/SheshaWorkflow/WorkflowHighLevelAssignee/Resolve`}
    {...props}
  />
);

export type UseWorkflowHighLevelAssigneeResolveProps = Omit<
  UseMutateProps<void, unknown, WorkflowHighLevelAssigneeResolveQueryParams, void, void>,
  'path' | 'verb'
>;

export const useWorkflowHighLevelAssigneeResolve = (props: UseWorkflowHighLevelAssigneeResolveProps) =>
  useMutate<void, unknown, WorkflowHighLevelAssigneeResolveQueryParams, void, void>(
    'POST',
    `/api/services/SheshaWorkflow/WorkflowHighLevelAssignee/Resolve`,
    props
  );
