name: shesha-reactjs-0.x.x

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '12.x'

jobs:

  # build the project
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout latest code
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          clean: true
      # setup node
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      # install dependencies
      - name: Install Dependencies
        run: npm install
      # build shesha-reactjs for pipeline
      - name: Build shesha-reactjs for Pipeline
      # build storybook
      - name: Build Storybook
        run: build-storybook
      # tag shesha-reactjs
      - name: Tag shesha-reactjs
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
      # # build shesha-reactjs for production
      # - name: Build shesha-reactjs for Production
      # # publish shesha-reactjs
      # - name: Publish shesha-reactjs
