name: shesha-reactjs-0.x.x

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '12.x'

jobs:

  # build the project
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout latest code
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          clean: true
      # setup node
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      # install dependencies
      - name: Install Dependencies
        run: npm install